// The DrawingML preset shapes (`prst`) from LibreOffice's table of their formulas
// (`shapePresets.json`, generated by scripts/make-shape-presets.mjs), resolved for a size
// or written back as ODF's enhanced geometry. Reached only from lazily loaded code.

import SHAPE_PRESETS from './shapePresets.json';
import { resolveGeometry, type ResolvedGeometry } from './enhancedGeometry';
import type { DrawingMlPreset } from './shapes';

type Entry = { adj?: [string, number][]; eq: string[]; path: string; sub?: number[]; text?: string };

const entry = (name: string): Entry | null =>
  Object.hasOwn(SHAPE_PRESETS, name) ? (SHAPE_PRESETS as unknown as Record<string, Entry>)[name] : null;

export const isPresetName = (name: string): boolean => !!entry(name);

/** The adjust values in the table's order, the file's own over the defaults. */
export function presetModifiers(p: DrawingMlPreset): number[] {
  return (entry(p.name)?.adj ?? []).map(([name, v]) => p.adj[name] ?? v);
}

/** The adjust values a list of `draw:modifiers` sets, named by the table; a default is no setting. */
export function presetAdjust(name: string, modifiers: number[]): Record<string, number> {
  return Object.fromEntries((entry(name)?.adj ?? []).flatMap(([n, v], i) =>
    Number.isFinite(modifiers[i]) && modifiers[i] !== v ? [[n, modifiers[i]]] : []));
}

/** A preset's outline and text area at `w`×`h` EMU; an empty path for a name the table lacks. */
export function presetGeometry(p: DrawingMlPreset, w: number, h: number): ResolvedGeometry {
  const e = entry(p.name);
  if (!e) return { path: '', textArea: null };
  return resolveGeometry({
    path: e.path,
    equations: Object.fromEntries(e.eq.map((f, i) => [`f${i}`, f])),
    modifiers: presetModifiers(p),
    viewBox: [0, 0, 0, 0], logW: w / 360, logH: h / 360, mirrorH: !!p.flipH, mirrorV: !!p.flipV,
    subViews: e.sub, textAreas: e.text,
  });
}

/**
 * The `<draw:enhanced-geometry>` LibreOffice itself writes for the preset: its type,
 * formulas and both paths — `draw:` without the arcs and shading only `drawooo:` knows.
 */
export function presetOdfGeometry(p: DrawingMlPreset): string | null {
  const e = entry(p.name);
  if (!e) return null;
  const plain = e.path.replace(/G(?: \S+){4}(?:(?: (?![A-Z]\b)\S+){4})*/g, '').replace(/ [HIJK](?= )/g, '')
    .replace(/\s+/g, ' ').trim();
  const mods = presetModifiers(p);
  return `<draw:enhanced-geometry svg:viewBox="0 0 0 0" draw:type="ooxml-${p.name}"`
    + ` draw:mirror-horizontal="${!!p.flipH}" draw:mirror-vertical="${!!p.flipV}"`
    + (mods.length ? ` draw:modifiers="${mods.join(' ')}"` : '')
    + (e.text ? ` draw:text-areas="${e.text}"` : '')
    + ` draw:enhanced-path="${plain}" drawooo:enhanced-path="${e.path}"`
    + (e.sub ? ` drawooo:sub-view-size="${e.sub.join(' ')}"` : '') + '>'
    + e.eq.map((f, i) => `<draw:equation draw:name="f${i}" draw:formula="${f}"/>`).join('')
    + '</draw:enhanced-geometry>';
}
